_target_: src.models.exp2_2_module.SalmonLitModule

integrated_resnet:
  _target_: src.models.components.exp2_model.IntegratedResNet
  architecture: "resnet18"
  num_classes: 10
rpu_config:
  _target_: aihwkit.simulator.presets.IdealizedPreset
  device:
    _target_: aihwkit.simulator.presets.devices.IdealizedPresetDevice
    dw_min: 0.0002
    dw_min_dtod: 0.0  # 수정됨
    dw_min_std: 0.0   # 수정됨
    up_down: 0.0
    up_down_dtod: 0.0  # 이미 0
    w_max: 1.0
    w_min: -1.0
    w_max_dtod: 0.0   # 수정됨
    w_min_dtod: 0.0   # 수정됨

# 4비트: 0.125
# 5비트: 0.0625
# 6비트: 0.03125
# 7비트: 0.015625
# 8비트: 0.0078125
# 9비트: 0.00390625
# 10비트: 0.001953125

# Optimizer settings
optimizer:
  lr: 0.01
  weight_decay: 0.0
  # SGD를 사용하므로, Adam에 특화된 betas, eps, amsgrad 매개변수는 제거
  momentum: 0.9  # SGD에 자주 사용되는 momentum 매개변수 추가
  # 필요한 경우 dampening과 nesterov 매개변수를 추가할 수 있습니다. 예시에서는 생략
  # dampening: 0  # 선택적
  # nesterov: False  # 선택적

compile: false

# Additional hyperparameters
model: "resnet18"
dataset: "cifar10"
epoch: 300
dataset_path: "data"
autoaugment: False
batchsize: 128
N_CLASSES: 10
opt_config : "AnalogSGD"
sch_config : "off-schedule"


