eqprop_track:
  _target_: src.utils.pycallbacks.WandbLoggerCallback
  on_step: True
  on_epoch: True
  log_options:
    "histogram": False
    "scalar": True
    "Vdrops": False
    "minimize": False
